# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ADORuntimeConnection'
    subscriptionId: '37666665-c573-4441-94e9-5e9fc392a441'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ADOTestDeploy-rg'
    location: 'Australia East'
    templateLocation: 'URL of the file'
    csmFileLink: "https://raw.githubusercontent.com/sudo-xource/AZInfraDeployment/main/CreateWebApp/azuredeploy.json?token=GHSAT0AAAAAABVGMB7G2VIGI2XQC2NE2MTOYUZ254A"
    overrideParameters: '-projectName myfirstpipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

